# Copyright 2025 The ChaosBlade Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosblade-box
  labels:
    name: chaosblade-box
    app: chaosblade-box
spec:
  selector:
    matchLabels:
      name: chaosblade-box
      app: chaosblade-box
  template:
    metadata:
      labels:
        name: chaosblade-box
        app: chaosblade-box
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      containers:
        - name: chaosblade-box
          image: {{ .Values.box.repository }}:{{ .Values.box.version }}
          imagePullPolicy: {{ .Values.box.pullPolicy }}
          env:
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - '--spring.datasource.url={{ .Values.spring.datasource.url }}'
            - '--spring.datasource.username={{ .Values.spring.datasource.username }}'
            - '--spring.datasource.password={{ .Values.spring.datasource.password }}'
            - '--chaos.function.sync.type={{ .Values.chaos.function.sync.type }}'
            - '--chaos.agent.version={{ .Values.chaos.agent.version }}'
            - '--chaos.agent.repository={{ .Values.chaos.agent.repository }}'
            - '--chaos.agent.url={{ .Values.chaos.agent.url }}'
            - '--chaos.agent.helm={{ .Values.chaos.agent.helm }}'
            {{- if .Values.chaos.prometheus.api }}
            - '--chaos.prometheus.api={{ .Values.chaos.prometheus.api }}'
            {{ end }}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /etc/hosts
              name: hosts

      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker-socket
        - hostPath:
            path: /etc/hosts
          name: hosts
      serviceAccountName: chaosblade-box
